trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: '/bin/bash -c "chmod -R 777 /srv/jekyll && JEKYLL_ENV=enterprise jekyll build --future"'
    detached: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/4f7e5548-1575-4b1d-acb9-c9baa0d52f50.zip'
    replaceExistingArchive: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure didsomeoneclone.me service connection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name $(AZURE_STORAGE_ACCOUNT_NAME) --account-key $(AZURE_STORAGE_ACCOUNT_KEY) --name 4f7e5548-1575-4b1d-acb9-c9baa0d52f50.zip --type block --file $(Build.ArtifactStagingDirectory)/4f7e5548-1575-4b1d-acb9-c9baa0d52f50.zip --container-name $(AZURE_STORAGE_CONTAINER_NAME) --overwrite'