trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/tmp/jekyll
      $(build.binariesDirectory):/tmp/jekyll/_site
    containerCommand: 'jekyll build --future'  # Change permissions to allow writing
    detached: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.binariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '/tmp/$(Build.BuildId).zip'
    replaceExistingArchive: true 
