trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: '/bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"'
    detached: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/4f7e5548-1575-4b1d-acb9-c9baa0d52f50.zip'
    replaceExistingArchive: true

- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/4f7e5548-1575-4b1d-acb9-c9baa0d52f50.zip'
    azureSubscription: 'Azure didsomeoneclone.me service connection'
    Destination: 'AzureBlob'
    storage: 'dscmarmstorage'
    ContainerName: 'management'

